CREATE TABLE "store_locations" (
  "id" SERIAL PRIMARY KEY,
  "store_id" int NOT NULL,
  "mall_id" int NOT NULL,
  "address" varchar(255) NOT NULL,
  "city" varchar(255) NOT NULL,
  "state" varchar(255) NOT NULL,
  "country_id" int NOT NULL,
  "zip" varchar(255) NOT NULL,
  "latitude" varchar DEFAULT NULL,
  "longitude" varchar DEFAULT NULL,
  "phone_no" varchar(20) DEFAULT NULL,
  "timezone" varchar(255) DEFAULT NULL,
  "isdeleted" boolean DEFAULT 'false',
  "isblocked" boolean DEFAULT 'false',
  "monday_start" time DEFAULT NULL,
  "monday_end" time DEFAULT NULL,
  "tuesday_start" time DEFAULT NULL,
  "tuesday_end" time DEFAULT NULL,
  "wednesday_start" time DEFAULT NULL,
  "wednesday_end" time DEFAULT NULL,
  "thursday_start" time DEFAULT NULL,
  "thursday_end" time DEFAULT NULL,
  "friday_start" time DEFAULT NULL,
  "friday_end" time DEFAULT NULL,
  "saturday_start" time DEFAULT NULL,
  "saturday_end" time DEFAULT NULL,
  "sunday_start" time DEFAULT NULL,
  "sunday_end" time DEFAULT NULL,
  "ip_address" varchar(255) DEFAULT NULL,
  "level" int DEFAULT NULL,
  "floor" varchar(255) DEFAULT NULL,
  "side" varchar(255) DEFAULT NULL,
  "user_id" int DEFAULT NULL,
  "map" varchar(255) DEFAULT NULL,
  "is_holiday" boolean DEFAULT 'false',
  "holiday_start_date" date DEFAULT NULL,
  "holiday_end_date" date DEFAULT NULL,
  "holiday_start_time" time DEFAULT NULL,
  "holiday_end_time" time DEFAULT NULL,
  "currency_id" int NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT fk_store_locations_store FOREIGN KEY (store_id) REFERENCES stores(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_store_locations_mall FOREIGN KEY (mall_id) REFERENCES malls(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_store_locations_country FOREIGN KEY (country_id) REFERENCES countries(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_store_locations_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_store_locations_currency FOREIGN KEY (currency_id) REFERENCES currencies(id) ON UPDATE CASCADE ON DELETE RESTRICT
)