CREATE TABLE "malls" (
  "id" SERIAL PRIMARY KEY,
  "parent_id" INT DEFAULT NULL,
  "name" VARCHAR NOT NULL,
  "mall_no" VARCHAR DEFAULT NULL,
  "address" VARCHAR NOT NULL,
  "city" VARCHAR NOT NULL,
  "state" VARCHAR NOT NULL,
  "country_id" int NOT NULL,
  "zip" VARCHAR NOT NULL,
  "phone_no" varchar(20) DEFAULT NULL,
  "latitude" varchar DEFAULT NULL,
  "longitude" varchar DEFAULT NULL,
  "banner_path" VARCHAR DEFAULT NULL,
  "isdeleted" boolean DEFAULT 'false',
  "isblocked" boolean DEFAULT 'false',
  "timezone" VARCHAR DEFAULT NULL,
  "monday_start" time DEFAULT NULL,
  "monday_end" time DEFAULT NULL,
  "tuesday_start" time DEFAULT NULL,
  "tuesday_end" time DEFAULT NULL,
  "wednesday_start" time DEFAULT NULL,
  "wednesday_end" time DEFAULT NULL,
  "thursday_start" time DEFAULT NULL,
  "thursday_end" time DEFAULT NULL,
  "friday_start" time DEFAULT NULL,
  "friday_end" time DEFAULT NULL,
  "saturday_start" time DEFAULT NULL,
  "saturday_end" time DEFAULT NULL,
  "sunday_start" time DEFAULT NULL,
  "sunday_end" time DEFAULT NULL,
  "user_id" int DEFAULT NULL,
  "map" VARCHAR DEFAULT NULL,
  "is_holiday" boolean DEFAULT 'false',
  "holiday_start_date" date DEFAULT NULL,
  "holiday_end_date" date DEFAULT NULL,
  "holiday_start_time" time DEFAULT NULL,
  "holiday_end_time" time DEFAULT NULL,
  "zone_id" int DEFAULT NULL,
  "ad_link" VARCHAR DEFAULT NULL,
   "created_at" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT fk_malls_parent FOREIGN KEY (parent_id) REFERENCES malls(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_malls_country FOREIGN KEY (country_id) REFERENCES countries(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_malls_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_malls_zone FOREIGN KEY (zone_id) REFERENCES zones(id) ON UPDATE CASCADE ON DELETE RESTRICT
)