// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: homePageImageLanguages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHomePageImageLanguage = `-- name: CreateHomePageImageLanguage :one
INSERT INTO home_page_image_languages (home_page_image_id, language_id, name)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateHomePageImageLanguageParams struct {
	HomePageImageID pgtype.Int4 `json:"home_page_image_id"`
	LanguageID      pgtype.Int4 `json:"language_id"`
	Name            pgtype.Text `json:"name"`
}

func (q *Queries) CreateHomePageImageLanguage(ctx context.Context, arg CreateHomePageImageLanguageParams) (int32, error) {
	row := q.db.QueryRow(ctx, createHomePageImageLanguage, arg.HomePageImageID, arg.LanguageID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteHomePageImageLanguage = `-- name: DeleteHomePageImageLanguage :one
DELETE FROM home_page_image_languages WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteHomePageImageLanguage(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteHomePageImageLanguage, id)
	err := row.Scan(&id)
	return id, err
}

const selectHomePageImageLanguages = `-- name: SelectHomePageImageLanguages :many
SELECT id, home_page_image_id, language_id, name, created_at FROM home_page_image_languages
`

func (q *Queries) SelectHomePageImageLanguages(ctx context.Context) ([]HomePageImageLanguage, error) {
	rows, err := q.db.Query(ctx, selectHomePageImageLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomePageImageLanguage{}
	for rows.Next() {
		var i HomePageImageLanguage
		if err := rows.Scan(
			&i.ID,
			&i.HomePageImageID,
			&i.LanguageID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomePageImageLanguage = `-- name: UpdateHomePageImageLanguage :one
UPDATE home_page_image_languages
SET
    home_page_image_id = $2,
    language_id = $3,
    name = $4
WHERE id = $1
RETURNING id
`

type UpdateHomePageImageLanguageParams struct {
	ID              int32       `json:"id"`
	HomePageImageID pgtype.Int4 `json:"home_page_image_id"`
	LanguageID      pgtype.Int4 `json:"language_id"`
	Name            pgtype.Text `json:"name"`
}

func (q *Queries) UpdateHomePageImageLanguage(ctx context.Context, arg UpdateHomePageImageLanguageParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateHomePageImageLanguage,
		arg.ID,
		arg.HomePageImageID,
		arg.LanguageID,
		arg.Name,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
