// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DevicetypeEnum string

const (
	DevicetypeEnumANDROID DevicetypeEnum = "ANDROID"
	DevicetypeEnumIOS     DevicetypeEnum = "IOS"
)

func (e *DevicetypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicetypeEnum(s)
	case string:
		*e = DevicetypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicetypeEnum: %T", src)
	}
	return nil
}

type NullDevicetypeEnum struct {
	DevicetypeEnum DevicetypeEnum `json:"devicetype_enum"`
	Valid          bool           `json:"valid"` // Valid is true if DevicetypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicetypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DevicetypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicetypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicetypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicetypeEnum), nil
}

type GenderEnum string

const (
	GenderEnumMale   GenderEnum = "Male"
	GenderEnumFemale GenderEnum = "Female"
)

func (e *GenderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderEnum(s)
	case string:
		*e = GenderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderEnum: %T", src)
	}
	return nil
}

type NullGenderEnum struct {
	GenderEnum GenderEnum `json:"gender_enum"`
	Valid      bool       `json:"valid"` // Valid is true if GenderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.GenderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderEnum), nil
}

type TypeEnum string

const (
	TypeEnumDepartment      TypeEnum = "Department"
	TypeEnumProductCategory TypeEnum = "ProductCategory"
	TypeEnumProduct         TypeEnum = "Product"
	TypeEnumBrand           TypeEnum = "Brand"
	TypeEnumFilter          TypeEnum = "Filter"
	TypeEnumMoreFIlter      TypeEnum = "More_FIlter"
	TypeEnumPrivate         TypeEnum = "Private"
	TypeEnumSku             TypeEnum = "Sku"
)

func (e *TypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypeEnum(s)
	case string:
		*e = TypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TypeEnum: %T", src)
	}
	return nil
}

type NullTypeEnum struct {
	TypeEnum TypeEnum `json:"type_enum"`
	Valid    bool     `json:"valid"` // Valid is true if TypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypeEnum), nil
}

type Brand struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Logo      pgtype.Text `json:"logo"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type BrandsLanguage struct {
	ID         int32       `json:"id"`
	BrandID    pgtype.Int4 `json:"brand_id"`
	LanguageID pgtype.Int4 `json:"language_id"`
	Name       string      `json:"name"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Competitor struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Logo      pgtype.Text `json:"logo"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type CompetitorLanguage struct {
	ID           int32       `json:"id"`
	CompetitorID pgtype.Int4 `json:"competitor_id"`
	LanguageID   pgtype.Int4 `json:"language_id"`
	Name         string      `json:"name"`
	CreatedAt    time.Time   `json:"created_at"`
}

type Contact struct {
	ID        int32       `json:"id"`
	Name      pgtype.Text `json:"name"`
	Email     string      `json:"email"`
	UserID    pgtype.Int4 `json:"user_id"`
	Subject   pgtype.Text `json:"subject"`
	Message   string      `json:"message"`
	CreatedAt time.Time   `json:"created_at"`
}

type ContentManagement struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type ContentManagementBanner struct {
	ID                  int32       `json:"id"`
	ContentManagementID pgtype.Int4 `json:"content_management_id"`
	Banner              string      `json:"banner"`
	BannerText          string      `json:"banner_text"`
	BannerLink          pgtype.Text `json:"banner_link"`
	CreatedAt           time.Time   `json:"created_at"`
}

type ContentManagementBannerLanguage struct {
	ID                  int32     `json:"id"`
	ContentManagementID int32     `json:"content_management_id"`
	LanguageID          int32     `json:"language_id"`
	Name                string    `json:"name"`
	Title               string    `json:"title"`
	Content             string    `json:"content"`
	CreatedAt           time.Time `json:"created_at"`
}

type ContentManagementLanguage struct {
	ID                  int32     `json:"id"`
	ContentManagementID int32     `json:"content_management_id"`
	LanguageID          int32     `json:"language_id"`
	Name                string    `json:"name"`
	Title               string    `json:"title"`
	Content             string    `json:"content"`
	CreatedAt           time.Time `json:"created_at"`
}

type ContentManagementMobile struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Title     string      `json:"title"`
	Link      pgtype.Text `json:"link"`
	LinkText  pgtype.Text `json:"link_text"`
	Content   string      `json:"content"`
	Isblocked pgtype.Bool `json:"isblocked"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	CreatedAt time.Time   `json:"created_at"`
}

type ContentManagementMobileLanguage struct {
	ID                        int32     `json:"id"`
	ContentManagementMobileID int32     `json:"content_management_mobile_id"`
	LanguageID                int32     `json:"language_id"`
	Title                     string    `json:"title"`
	Link                      string    `json:"link"`
	LinkText                  string    `json:"link_text"`
	Content                   string    `json:"content"`
	CreatedAt                 time.Time `json:"created_at"`
}

type Country struct {
	ID          int32     `json:"id"`
	Iso2        string    `json:"iso2"`
	ShortName   string    `json:"short_name"`
	LongName    string    `json:"long_name"`
	Iso3        string    `json:"iso3"`
	Numcode     string    `json:"numcode"`
	UnMember    string    `json:"un_member"`
	CallingCode string    `json:"calling_code"`
	Cctld       string    `json:"cctld"`
	CreatedAt   time.Time `json:"created_at"`
}

type Coupon struct {
	ID          int32          `json:"id"`
	StoreID     pgtype.Int4    `json:"store_id"`
	BrandID     pgtype.Int4    `json:"brand_id"`
	ProductID   pgtype.Int4    `json:"product_id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description pgtype.Text    `json:"description"`
	Path        pgtype.Text    `json:"path"`
	Isdeleted   pgtype.Bool    `json:"isdeleted"`
	Isblocked   pgtype.Bool    `json:"isblocked"`
	UserID      int32          `json:"user_id"`
	Price       pgtype.Numeric `json:"price"`
	Ispercent   int32          `json:"ispercent"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	UnitID      pgtype.Int4    `json:"unit_id"`
	Qty         pgtype.Int4    `json:"qty"`
	CreatedAt   time.Time      `json:"created_at"`
}

type CouponCondition struct {
	ID        int32        `json:"id"`
	CouponID  int32        `json:"coupon_id"`
	Idx       int32        `json:"idx"`
	Type      NullTypeEnum `json:"type"`
	TypeID    string       `json:"type_id"`
	CreatedAt time.Time    `json:"created_at"`
}

type CouponLanguage struct {
	ID          int32       `json:"id"`
	CouponID    pgtype.Int4 `json:"coupon_id"`
	LanguageID  pgtype.Int4 `json:"language_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Disclaimer  string      `json:"disclaimer"`
	CreatedAt   time.Time   `json:"created_at"`
}

type CouponProduct struct {
	ID        int32       `json:"id"`
	CouponID  pgtype.Int4 `json:"coupon_id"`
	ProductID pgtype.Int4 `json:"product_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Currency struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Symbol    string      `json:"symbol"`
	Isdefault pgtype.Bool `json:"isdefault"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type Deal struct {
	ID        int32       `json:"id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Lft       pgtype.Int4 `json:"lft"`
	Rght      pgtype.Int4 `json:"rght"`
	Name      pgtype.Text `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
}

type DealsLanguage struct {
	ID         int32       `json:"id"`
	DealsID    pgtype.Int4 `json:"deals_id"`
	LanguageID pgtype.Int4 `json:"language_id"`
	Name       pgtype.Text `json:"name"`
	CreatedAt  time.Time   `json:"created_at"`
}

type DisLikeCount struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	OfferID   int32     `json:"offer_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Feedback struct {
	ID        int32       `json:"id"`
	Email     string      `json:"email"`
	Message   string      `json:"message"`
	UserID    pgtype.Int4 `json:"user_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type HomeBanner struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	UrlType     string      `json:"url_type"`
	Description string      `json:"description"`
	Param       pgtype.Text `json:"param"`
	Image       string      `json:"image"`
	Isdefault   pgtype.Bool `json:"isdefault"`
	Sequence    pgtype.Int4 `json:"sequence"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Isdeleted   pgtype.Bool `json:"isdeleted"`
	Isblocked   pgtype.Bool `json:"isblocked"`
	CreatedAt   time.Time   `json:"created_at"`
}

type HomeBannerLanguage struct {
	ID           int32       `json:"id"`
	HomeBannerID pgtype.Int4 `json:"home_banner_id"`
	LanguageID   pgtype.Int4 `json:"language_id"`
	Name         pgtype.Text `json:"name"`
	Description  pgtype.Text `json:"description"`
	CreatedAt    time.Time   `json:"created_at"`
}

type HomePageIcon struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	Type      pgtype.Text `json:"type"`
	Value     string      `json:"value"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type HomePageIconLanguage struct {
	ID             int32       `json:"id"`
	HomePageIconID pgtype.Int4 `json:"home_page_icon_id"`
	LanguageID     pgtype.Int4 `json:"language_id"`
	Name           pgtype.Text `json:"name"`
	CreatedAt      time.Time   `json:"created_at"`
}

type HomePageImage struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Path      string      `json:"path"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type HomePageImageLanguage struct {
	ID              int32       `json:"id"`
	HomePageImageID pgtype.Int4 `json:"home_page_image_id"`
	LanguageID      pgtype.Int4 `json:"language_id"`
	Name            pgtype.Text `json:"name"`
	CreatedAt       time.Time   `json:"created_at"`
}

type ImportFlow struct {
	ID            int32       `json:"id"`
	FileName      string      `json:"file_name"`
	NoRows        pgtype.Int4 `json:"no_rows"`
	Created       time.Time   `json:"created"`
	Modified      time.Time   `json:"modified"`
	Status        string      `json:"status"`
	NoError       pgtype.Int4 `json:"no_error"`
	Note          string      `json:"note"`
	LogFile       pgtype.Text `json:"log_file"`
	CompletedFile pgtype.Text `json:"completed_file"`
	CreatedAt     time.Time   `json:"created_at"`
}

type Language struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Code      string      `json:"code"`
	Isdefault pgtype.Bool `json:"isdefault"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type LikeCount struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	OfferID   int32     `json:"offer_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Mall struct {
	ID               int32       `json:"id"`
	ParentID         pgtype.Int4 `json:"parent_id"`
	Name             string      `json:"name"`
	MallNo           pgtype.Text `json:"mall_no"`
	Address          string      `json:"address"`
	City             string      `json:"city"`
	State            string      `json:"state"`
	CountryID        int32       `json:"country_id"`
	Zip              string      `json:"zip"`
	PhoneNo          pgtype.Text `json:"phone_no"`
	Latitude         pgtype.Text `json:"latitude"`
	Longitude        pgtype.Text `json:"longitude"`
	BannerPath       pgtype.Text `json:"banner_path"`
	Isdeleted        pgtype.Bool `json:"isdeleted"`
	Isblocked        pgtype.Bool `json:"isblocked"`
	Timezone         pgtype.Text `json:"timezone"`
	MondayStart      pgtype.Time `json:"monday_start"`
	MondayEnd        pgtype.Time `json:"monday_end"`
	TuesdayStart     pgtype.Time `json:"tuesday_start"`
	TuesdayEnd       pgtype.Time `json:"tuesday_end"`
	WednesdayStart   pgtype.Time `json:"wednesday_start"`
	WednesdayEnd     pgtype.Time `json:"wednesday_end"`
	ThursdayStart    pgtype.Time `json:"thursday_start"`
	ThursdayEnd      pgtype.Time `json:"thursday_end"`
	FridayStart      pgtype.Time `json:"friday_start"`
	FridayEnd        pgtype.Time `json:"friday_end"`
	SaturdayStart    pgtype.Time `json:"saturday_start"`
	SaturdayEnd      pgtype.Time `json:"saturday_end"`
	SundayStart      pgtype.Time `json:"sunday_start"`
	SundayEnd        pgtype.Time `json:"sunday_end"`
	UserID           pgtype.Int4 `json:"user_id"`
	Map              pgtype.Text `json:"map"`
	IsHoliday        pgtype.Bool `json:"is_holiday"`
	HolidayStartDate pgtype.Date `json:"holiday_start_date"`
	HolidayEndDate   pgtype.Date `json:"holiday_end_date"`
	HolidayStartTime pgtype.Time `json:"holiday_start_time"`
	HolidayEndTime   pgtype.Time `json:"holiday_end_time"`
	ZoneID           pgtype.Int4 `json:"zone_id"`
	AdLink           pgtype.Text `json:"ad_link"`
	CreatedAt        time.Time   `json:"created_at"`
}

type MallLanguage struct {
	ID         int32     `json:"id"`
	MallID     int32     `json:"mall_id"`
	LanguageID int32     `json:"language_id"`
	Name       string    `json:"name"`
	Address    string    `json:"address"`
	City       string    `json:"city"`
	State      string    `json:"state"`
	Zip        string    `json:"zip"`
	PhoneNo    string    `json:"phone_no"`
	CreatedAt  time.Time `json:"created_at"`
}

type MallView struct {
	ID         int32       `json:"id"`
	UserID     int32       `json:"user_id"`
	MallID     int32       `json:"mall_id"`
	StoreID    int32       `json:"store_id"`
	Visited    pgtype.Date `json:"visited"`
	DeviceID   pgtype.Text `json:"device_id"`
	FromDevice pgtype.Bool `json:"from_device"`
	IsPhysical pgtype.Bool `json:"is_physical"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Offer struct {
	ID          int32       `json:"id"`
	DealNo      pgtype.Text `json:"deal_no"`
	StoreID     pgtype.Int4 `json:"store_id"`
	ProductID   pgtype.Int4 `json:"product_id"`
	Name        string      `json:"name"`
	Path        pgtype.Text `json:"path"`
	Description pgtype.Text `json:"description"`
	Isblocked   pgtype.Bool `json:"isblocked"`
	Isdeleted   pgtype.Bool `json:"isdeleted"`
	UserID      pgtype.Int4 `json:"user_id"`
	CreatedAt   time.Time   `json:"created_at"`
}

type OfferView struct {
	ID              int32       `json:"id"`
	ProductID       int32       `json:"product_id"`
	OfferID         int32       `json:"offer_id"`
	MallID          int32       `json:"mall_id"`
	StoreID         int32       `json:"store_id"`
	StoreLocationID int32       `json:"store_location_id"`
	UserID          int32       `json:"user_id"`
	Viewed          pgtype.Int4 `json:"viewed"`
	ViewDate        pgtype.Date `json:"view_date"`
	IsClicked       pgtype.Bool `json:"is_clicked"`
	CreatedAt       time.Time   `json:"created_at"`
}

type OffersCategory struct {
	ID        int32       `json:"id"`
	DealID    pgtype.Int4 `json:"deal_id"`
	OfferID   pgtype.Int4 `json:"offer_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Product struct {
	ID                int32       `json:"id"`
	BrandID           pgtype.Int4 `json:"brand_id"`
	ProductCategoryID pgtype.Int4 `json:"product_category_id"`
	Name              string      `json:"name"`
	Sku               string      `json:"sku"`
	Description       pgtype.Text `json:"description"`
	ShortDescription  pgtype.Text `json:"short_description"`
	NewFrom           pgtype.Date `json:"new_from"`
	NewEnd            pgtype.Date `json:"new_end"`
	Isdeleted         pgtype.Bool `json:"isdeleted"`
	Isblocked         pgtype.Bool `json:"isblocked"`
	Isbestseller      pgtype.Bool `json:"isbestseller"`
	Isfeatured        pgtype.Bool `json:"isfeatured"`
	MetaTitle         string      `json:"meta_title"`
	MetaKeywords      string      `json:"meta_keywords"`
	MetaDescription   string      `json:"meta_description"`
	Price             int32       `json:"price"`
	UnitID            pgtype.Int4 `json:"unit_id"`
	CreatedAt         time.Time   `json:"created_at"`
}

type ProductCategory struct {
	ID        int32       `json:"id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Lft       pgtype.Int4 `json:"lft"`
	Rght      pgtype.Int4 `json:"rght"`
	Name      pgtype.Text `json:"name"`
	Logo      pgtype.Text `json:"logo"`
	StoreID   pgtype.Int4 `json:"store_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type ProductCategoryLanguage struct {
	ID                int32     `json:"id"`
	LanguageID        int32     `json:"language_id"`
	ProductCategoryID int32     `json:"product_category_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type ProductCategoryMap struct {
	ID                int32     `json:"id"`
	ProductID         int32     `json:"product_id"`
	ProductCategoryID int32     `json:"product_category_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type ProductCompetitor struct {
	ID              int32          `json:"id"`
	ProductID       int32          `json:"product_id"`
	CompetitorID    int32          `json:"competitor_id"`
	StoreLocationID int32          `json:"store_location_id"`
	Price           pgtype.Numeric `json:"price"`
	CreatedAt       time.Time      `json:"created_at"`
}

type ProductImage struct {
	ID        int32       `json:"id"`
	ProductID int32       `json:"product_id"`
	Image     string      `json:"image"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	Isdefault pgtype.Bool `json:"isdefault"`
	CreatedAt time.Time   `json:"created_at"`
}

type ProductLanguage struct {
	ID               int32          `json:"id"`
	ProductID        pgtype.Int4    `json:"product_id"`
	LanguageID       pgtype.Int4    `json:"language_id"`
	Name             string         `json:"name"`
	Sku              string         `json:"sku"`
	Description      pgtype.Text    `json:"description"`
	ShortDescription pgtype.Text    `json:"short_description"`
	Weight           pgtype.Numeric `json:"weight"`
	MetaTitle        string         `json:"meta_title"`
	MetaKeywords     string         `json:"meta_keywords"`
	MetaDescription  string         `json:"meta_description"`
	CreatedAt        time.Time      `json:"created_at"`
}

type ProductStoreLocation struct {
	ID              int32       `json:"id"`
	ProductID       pgtype.Int4 `json:"product_id"`
	StoreLocationID pgtype.Int4 `json:"store_location_id"`
	CreatedAt       time.Time   `json:"created_at"`
}

type ProductTest struct {
	ID                int32          `json:"id"`
	BrandID           pgtype.Int4    `json:"brand_id"`
	ProductCategoryID pgtype.Int4    `json:"product_category_id"`
	Name              string         `json:"name"`
	Sku               string         `json:"sku"`
	Description       pgtype.Text    `json:"description"`
	ShortDescription  pgtype.Text    `json:"short_description"`
	Weight            pgtype.Numeric `json:"weight"`
	NewFrom           pgtype.Date    `json:"new_from"`
	NewEnd            pgtype.Date    `json:"new_end"`
	Isdeleted         pgtype.Bool    `json:"isdeleted"`
	Isblocked         pgtype.Bool    `json:"isblocked"`
	Isbestseller      pgtype.Bool    `json:"isbestseller"`
	Isfeatured        pgtype.Bool    `json:"isfeatured"`
	MetaTitle         string         `json:"meta_title"`
	MetaKeywords      string         `json:"meta_keywords"`
	MetaDescription   string         `json:"meta_description"`
	Price             pgtype.Numeric `json:"price"`
	UnitID            pgtype.Int4    `json:"unit_id"`
	CreatedAt         time.Time      `json:"created_at"`
}

type PushNotification struct {
	ID              int32       `json:"id"`
	DeviceID        string      `json:"device_id"`
	StoreLocationID int32       `json:"store_location_id"`
	OfferID         int32       `json:"offer_id"`
	IsSent          pgtype.Bool `json:"is_sent"`
	IsClicked       pgtype.Bool `json:"is_clicked"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Role struct {
	ID                      int32       `json:"id"`
	Name                    string      `json:"name"`
	MallsAdd                pgtype.Bool `json:"malls_add"`
	MallsView               pgtype.Bool `json:"malls_view"`
	MallsEdit               pgtype.Bool `json:"malls_edit"`
	MallsDelete             pgtype.Bool `json:"malls_delete"`
	StoresAdd               pgtype.Bool `json:"stores_add"`
	StoresView              pgtype.Bool `json:"stores_view"`
	StoresEdit              pgtype.Bool `json:"stores_edit"`
	StoresDelete            pgtype.Bool `json:"stores_delete"`
	ProductsAdd             pgtype.Bool `json:"products_add"`
	ProductsView            pgtype.Bool `json:"products_view"`
	ProductsEdit            pgtype.Bool `json:"products_edit"`
	ProductsDelete          pgtype.Bool `json:"products_delete"`
	ProductsPrice           pgtype.Bool `json:"products_price"`
	UsersView               pgtype.Bool `json:"users_view"`
	UsersAdd                pgtype.Bool `json:"users_add"`
	UsersEdit               pgtype.Bool `json:"users_edit"`
	UsersDelete             pgtype.Bool `json:"users_delete"`
	UsersRole               pgtype.Bool `json:"users_role"`
	AuditsUser              pgtype.Bool `json:"audits_user"`
	AuditsProduct           pgtype.Bool `json:"audits_product"`
	StoreLocationsView      pgtype.Bool `json:"store_locations_view"`
	StoreLocationsAdd       pgtype.Bool `json:"store_locations_add"`
	StoreLocationsEdit      pgtype.Bool `json:"store_locations_edit"`
	StoreLocationsDelete    pgtype.Bool `json:"store_locations_delete"`
	OffersAdd               pgtype.Bool `json:"offers_add"`
	OffersEdit              pgtype.Bool `json:"offers_edit"`
	OffersDelete            pgtype.Bool `json:"offers_delete"`
	OffersView              pgtype.Bool `json:"offers_view"`
	ReportsView             pgtype.Bool `json:"reports_view"`
	BrandsView              pgtype.Bool `json:"brands_view"`
	BrandsAdd               pgtype.Bool `json:"brands_add"`
	BrandsEdit              pgtype.Bool `json:"brands_edit"`
	BrandsDelete            pgtype.Bool `json:"brands_delete"`
	UnitsView               pgtype.Bool `json:"units_view"`
	UnitsAdd                pgtype.Bool `json:"units_add"`
	UnitsEdit               pgtype.Bool `json:"units_edit"`
	UnitsDelete             pgtype.Bool `json:"units_delete"`
	ProductCategoriesView   pgtype.Bool `json:"product_categories_view"`
	ProductCategoriesAdd    pgtype.Bool `json:"product_categories_add"`
	ProductCategoriesEdit   pgtype.Bool `json:"product_categories_edit"`
	ProductCategoriesDelete pgtype.Bool `json:"product_categories_delete"`
	CreatedAt               time.Time   `json:"created_at"`
}

type ShareCount struct {
	ID                int32       `json:"id"`
	LanguageID        int32       `json:"language_id"`
	ProductCategoryID int32       `json:"product_category_id"`
	ShareType         pgtype.Text `json:"share_type"`
	CreatedAt         time.Time   `json:"created_at"`
}

type Store struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	StoreNo     pgtype.Text `json:"store_no"`
	Description string      `json:"description"`
	Logo        pgtype.Text `json:"logo"`
	PhoneNo     pgtype.Text `json:"phone_no"`
	Isdeleted   pgtype.Bool `json:"isdeleted"`
	Isblocked   pgtype.Bool `json:"isblocked"`
	UserID      pgtype.Int4 `json:"user_id"`
	Icon        pgtype.Text `json:"icon"`
	CreatedAt   time.Time   `json:"created_at"`
}

type StoreBusinessHour struct {
	ID              int32       `json:"id"`
	StoreLocationID int32       `json:"store_location_id"`
	Day             string      `json:"day"`
	StartTime       pgtype.Date `json:"start_time"`
	EndTime         pgtype.Date `json:"end_time"`
	CreatedAt       time.Time   `json:"created_at"`
}

type StoreCategory struct {
	ID        int32     `json:"id"`
	DealID    int32     `json:"deal_id"`
	StoreID   int32     `json:"store_id"`
	CreatedAt time.Time `json:"created_at"`
}

type StoreLanguage struct {
	ID          int32     `json:"id"`
	LanguageID  int32     `json:"language_id"`
	StoreID     int32     `json:"store_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type StoreLocation struct {
	ID               int32       `json:"id"`
	StoreID          int32       `json:"store_id"`
	MallID           int32       `json:"mall_id"`
	Address          string      `json:"address"`
	City             string      `json:"city"`
	State            string      `json:"state"`
	CountryID        int32       `json:"country_id"`
	Zip              string      `json:"zip"`
	Latitude         pgtype.Text `json:"latitude"`
	Longitude        pgtype.Text `json:"longitude"`
	PhoneNo          pgtype.Text `json:"phone_no"`
	Timezone         pgtype.Text `json:"timezone"`
	Isdeleted        pgtype.Bool `json:"isdeleted"`
	Isblocked        pgtype.Bool `json:"isblocked"`
	MondayStart      pgtype.Time `json:"monday_start"`
	MondayEnd        pgtype.Time `json:"monday_end"`
	TuesdayStart     pgtype.Time `json:"tuesday_start"`
	TuesdayEnd       pgtype.Time `json:"tuesday_end"`
	WednesdayStart   pgtype.Time `json:"wednesday_start"`
	WednesdayEnd     pgtype.Time `json:"wednesday_end"`
	ThursdayStart    pgtype.Time `json:"thursday_start"`
	ThursdayEnd      pgtype.Time `json:"thursday_end"`
	FridayStart      pgtype.Time `json:"friday_start"`
	FridayEnd        pgtype.Time `json:"friday_end"`
	SaturdayStart    pgtype.Time `json:"saturday_start"`
	SaturdayEnd      pgtype.Time `json:"saturday_end"`
	SundayStart      pgtype.Time `json:"sunday_start"`
	SundayEnd        pgtype.Time `json:"sunday_end"`
	IpAddress        pgtype.Text `json:"ip_address"`
	Level            pgtype.Int4 `json:"level"`
	Floor            pgtype.Text `json:"floor"`
	Side             pgtype.Text `json:"side"`
	UserID           pgtype.Int4 `json:"user_id"`
	Map              pgtype.Text `json:"map"`
	IsHoliday        pgtype.Bool `json:"is_holiday"`
	HolidayStartDate pgtype.Date `json:"holiday_start_date"`
	HolidayEndDate   pgtype.Date `json:"holiday_end_date"`
	HolidayStartTime pgtype.Time `json:"holiday_start_time"`
	HolidayEndTime   pgtype.Time `json:"holiday_end_time"`
	CurrencyID       int32       `json:"currency_id"`
	CreatedAt        time.Time   `json:"created_at"`
}

type StoreLocationCoupon struct {
	ID              int32          `json:"id"`
	StoreLocationID int32          `json:"store_location_id"`
	ProductID       int32          `json:"product_id"`
	CouponID        int32          `json:"coupon_id"`
	Price           pgtype.Numeric `json:"price"`
	CouponPrice     pgtype.Numeric `json:"coupon_price"`
	IsPercent       pgtype.Bool    `json:"is_percent"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	Sequence        pgtype.Int4    `json:"sequence"`
	Isblocked       pgtype.Bool    `json:"isblocked"`
	Isdeleted       pgtype.Bool    `json:"isdeleted"`
	CreatedAt       time.Time      `json:"created_at"`
}

type StoreLocationHoliday struct {
	ID              int32       `json:"id"`
	StoreLocationID int32       `json:"store_location_id"`
	Name            string      `json:"name"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	CreatedAt       time.Time   `json:"created_at"`
}

type StoreLocationOffer struct {
	ID              int32          `json:"id"`
	StoreLocationID int32          `json:"store_location_id"`
	ProductID       int32          `json:"product_id"`
	OfferID         int32          `json:"offer_id"`
	Price           pgtype.Numeric `json:"price"`
	OfferedPrice    pgtype.Numeric `json:"offered_price"`
	IsPercent       pgtype.Bool    `json:"is_percent"`
	StartDate       pgtype.Date    `json:"start_date"`
	EndDate         pgtype.Date    `json:"end_date"`
	Sequence        pgtype.Int4    `json:"sequence"`
	Isblocked       pgtype.Bool    `json:"isblocked"`
	Isdeleted       pgtype.Bool    `json:"isdeleted"`
	Priority        pgtype.Bool    `json:"priority"`
	Weight          pgtype.Text    `json:"weight"`
	UnitID          int32          `json:"unit_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

type StoreNameCategory struct {
	ID        int32       `json:"id"`
	ParentID  pgtype.Int4 `json:"parent_id"`
	Lft       pgtype.Int4 `json:"lft"`
	Rght      pgtype.Int4 `json:"rght"`
	Name      pgtype.Text `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
}

type Subscription struct {
	ID        int32     `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	MallID    int32     `json:"mall_id"`
	Zip       string    `json:"zip"`
	CreatedAt time.Time `json:"created_at"`
}

type Unit struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type UnitLanguage struct {
	ID         int32     `json:"id"`
	UnitID     int32     `json:"unit_id"`
	LanguageID int32     `json:"language_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID            int32          `json:"id"`
	FirstName     string         `json:"first_name"`
	LastName      string         `json:"last_name"`
	Gender        GenderEnum     `json:"gender"`
	Dob           pgtype.Date    `json:"dob"`
	Address       string         `json:"address"`
	City          string         `json:"city"`
	State         string         `json:"state"`
	CountryID     pgtype.Int4    `json:"country_id"`
	Zip           string         `json:"zip"`
	MobileNo      string         `json:"mobile_no"`
	Email         string         `json:"email"`
	Username      string         `json:"username"`
	Password      string         `json:"password"`
	UserType      pgtype.Text    `json:"user_type"`
	Isdeleted     pgtype.Bool    `json:"isdeleted"`
	Isblocked     pgtype.Bool    `json:"isblocked"`
	Status        pgtype.Bool    `json:"status"`
	Latitude      pgtype.Numeric `json:"latitude"`
	Longitude     pgtype.Numeric `json:"longitude"`
	Photo         pgtype.Text    `json:"photo"`
	FacebookID    pgtype.Text    `json:"facebook_id"`
	GoogleID      pgtype.Text    `json:"google_id"`
	CreatedAt     time.Time      `json:"created_at"`
	LastLoginTime time.Time      `json:"last_login_time"`
}

type UserAction struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	SaveType        string      `json:"save_type"`
	Tablename       string      `json:"tablename"`
	AutoincrementID pgtype.Int4 `json:"autoincrement_id"`
	Fieldname       string      `json:"fieldname"`
	Value           string      `json:"value"`
	OldValue        pgtype.Text `json:"old_value"`
	Note            string      `json:"note"`
	CreatedAt       time.Time   `json:"created_at"`
}

type UserCoupon struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	CouponID  int32     `json:"coupon_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserDevice struct {
	ID          int32          `json:"id"`
	UserID      int32          `json:"user_id"`
	DeviceID    string         `json:"device_id"`
	DeviceType  DevicetypeEnum `json:"device_type"`
	Wuid        pgtype.Text    `json:"wuid"`
	DeviceToken pgtype.Text    `json:"device_token"`
	CreatedAt   time.Time      `json:"created_at"`
}

type UserEvent struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	Name      string      `json:"name"`
	Date      pgtype.Date `json:"date"`
	CreatedAt time.Time   `json:"created_at"`
}

type UserFavouriteStore struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	StoreID   int32       `json:"store_id"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}

type UserLog struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	MallID    int32       `json:"mall_id"`
	StoreID   int32       `json:"store_id"`
	OfferID   int32       `json:"offer_id"`
	Name      string      `json:"name"`
	Text      string      `json:"text"`
	Isblocked pgtype.Bool `json:"isblocked"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	CreatedAt time.Time   `json:"created_at"`
}

type UserMall struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	MallID    int32     `json:"mall_id"`
	DeviceID  string    `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserMallPermission struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	MallID    int32     `json:"mall_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserRole struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	RoleID    int32     `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserSetting struct {
	ID          int32       `json:"id"`
	UserID      int32       `json:"user_id"`
	MallRadius  pgtype.Int4 `json:"mall_radius"`
	StoreRadius pgtype.Int4 `json:"store_radius"`
	CreatedAt   time.Time   `json:"created_at"`
}

type UserShopingList struct {
	ID                    int32     `json:"id"`
	UserShopingListNameID int32     `json:"user_shoping_list_name_id"`
	ProductID             int32     `json:"product_id"`
	UserID                int32     `json:"user_id"`
	StoreLocationID       int32     `json:"store_location_id"`
	Qty                   int32     `json:"qty"`
	CreatedAt             time.Time `json:"created_at"`
}

type UserShoppingListName struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	Name      string      `json:"name"`
	HowObtain pgtype.Text `json:"how_obtain"`
	Frequency pgtype.Bool `json:"frequency"`
	Type      pgtype.Text `json:"type"`
	Isnotify  pgtype.Bool `json:"isnotify"`
	CreatedAt time.Time   `json:"created_at"`
}

type UserStore struct {
	ID              int32     `json:"id"`
	UserID          int32     `json:"user_id"`
	StoreLocationID int32     `json:"store_location_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type UserWishlist struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	ProductID       int32       `json:"product_id"`
	StoreLocationID pgtype.Int4 `json:"store_location_id"`
	WishPrice       float64     `json:"wish_price"`
	MaxPrice        float64     `json:"max_price"`
	Immediately     pgtype.Bool `json:"immediately"`
	DateTill        pgtype.Date `json:"date_till"`
	CreatedAt       time.Time   `json:"created_at"`
}

type Zone struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	State     string      `json:"state"`
	Isdeleted pgtype.Bool `json:"isdeleted"`
	Isblocked pgtype.Bool `json:"isblocked"`
	CreatedAt time.Time   `json:"created_at"`
}
