// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: storeLocations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreLocation = `-- name: CreateStoreLocation :one
INSERT INTO store_locations (
    store_id,
    mall_id,
    address,
    city,
    state,
    country_id,
    zip,
    latitude,
    longitude,
    phone_no,
    timezone,
    isdeleted,
    isblocked,
    monday_start,
    monday_end,
    tuesday_start,
    tuesday_end,
    wednesday_start,
    wednesday_end,
    thursday_start,
    thursday_end,
    friday_start,
    friday_end,
    saturday_start,
    saturday_end,
    sunday_start,
    sunday_end,
    ip_address,
    level,
    floor,
    side,
    user_id,
    map,
    is_holiday,
    holiday_start_date,
    holiday_end_date,
    holiday_start_time,
    holiday_end_time,
    currency_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39
)
RETURNING id
`

type CreateStoreLocationParams struct {
	StoreID          int32       `json:"store_id"`
	MallID           int32       `json:"mall_id"`
	Address          string      `json:"address"`
	City             string      `json:"city"`
	State            string      `json:"state"`
	CountryID        int32       `json:"country_id"`
	Zip              string      `json:"zip"`
	Latitude         pgtype.Text `json:"latitude"`
	Longitude        pgtype.Text `json:"longitude"`
	PhoneNo          pgtype.Text `json:"phone_no"`
	Timezone         pgtype.Text `json:"timezone"`
	Isdeleted        pgtype.Bool `json:"isdeleted"`
	Isblocked        pgtype.Bool `json:"isblocked"`
	MondayStart      pgtype.Time `json:"monday_start"`
	MondayEnd        pgtype.Time `json:"monday_end"`
	TuesdayStart     pgtype.Time `json:"tuesday_start"`
	TuesdayEnd       pgtype.Time `json:"tuesday_end"`
	WednesdayStart   pgtype.Time `json:"wednesday_start"`
	WednesdayEnd     pgtype.Time `json:"wednesday_end"`
	ThursdayStart    pgtype.Time `json:"thursday_start"`
	ThursdayEnd      pgtype.Time `json:"thursday_end"`
	FridayStart      pgtype.Time `json:"friday_start"`
	FridayEnd        pgtype.Time `json:"friday_end"`
	SaturdayStart    pgtype.Time `json:"saturday_start"`
	SaturdayEnd      pgtype.Time `json:"saturday_end"`
	SundayStart      pgtype.Time `json:"sunday_start"`
	SundayEnd        pgtype.Time `json:"sunday_end"`
	IpAddress        pgtype.Text `json:"ip_address"`
	Level            pgtype.Int4 `json:"level"`
	Floor            pgtype.Text `json:"floor"`
	Side             pgtype.Text `json:"side"`
	UserID           pgtype.Int4 `json:"user_id"`
	Map              pgtype.Text `json:"map"`
	IsHoliday        pgtype.Bool `json:"is_holiday"`
	HolidayStartDate pgtype.Date `json:"holiday_start_date"`
	HolidayEndDate   pgtype.Date `json:"holiday_end_date"`
	HolidayStartTime pgtype.Time `json:"holiday_start_time"`
	HolidayEndTime   pgtype.Time `json:"holiday_end_time"`
	CurrencyID       int32       `json:"currency_id"`
}

func (q *Queries) CreateStoreLocation(ctx context.Context, arg CreateStoreLocationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStoreLocation,
		arg.StoreID,
		arg.MallID,
		arg.Address,
		arg.City,
		arg.State,
		arg.CountryID,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.PhoneNo,
		arg.Timezone,
		arg.Isdeleted,
		arg.Isblocked,
		arg.MondayStart,
		arg.MondayEnd,
		arg.TuesdayStart,
		arg.TuesdayEnd,
		arg.WednesdayStart,
		arg.WednesdayEnd,
		arg.ThursdayStart,
		arg.ThursdayEnd,
		arg.FridayStart,
		arg.FridayEnd,
		arg.SaturdayStart,
		arg.SaturdayEnd,
		arg.SundayStart,
		arg.SundayEnd,
		arg.IpAddress,
		arg.Level,
		arg.Floor,
		arg.Side,
		arg.UserID,
		arg.Map,
		arg.IsHoliday,
		arg.HolidayStartDate,
		arg.HolidayEndDate,
		arg.HolidayStartTime,
		arg.HolidayEndTime,
		arg.CurrencyID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteStoreLocation = `-- name: DeleteStoreLocation :one
DELETE FROM store_locations WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteStoreLocation(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteStoreLocation, id)
	err := row.Scan(&id)
	return id, err
}

const selectStoreLocations = `-- name: SelectStoreLocations :many
SELECT id, store_id, mall_id, address, city, state, country_id, zip, latitude, longitude, phone_no, timezone, isdeleted, isblocked, monday_start, monday_end, tuesday_start, tuesday_end, wednesday_start, wednesday_end, thursday_start, thursday_end, friday_start, friday_end, saturday_start, saturday_end, sunday_start, sunday_end, ip_address, level, floor, side, user_id, map, is_holiday, holiday_start_date, holiday_end_date, holiday_start_time, holiday_end_time, currency_id, created_at FROM store_locations
`

func (q *Queries) SelectStoreLocations(ctx context.Context) ([]StoreLocation, error) {
	rows, err := q.db.Query(ctx, selectStoreLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoreLocation{}
	for rows.Next() {
		var i StoreLocation
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.MallID,
			&i.Address,
			&i.City,
			&i.State,
			&i.CountryID,
			&i.Zip,
			&i.Latitude,
			&i.Longitude,
			&i.PhoneNo,
			&i.Timezone,
			&i.Isdeleted,
			&i.Isblocked,
			&i.MondayStart,
			&i.MondayEnd,
			&i.TuesdayStart,
			&i.TuesdayEnd,
			&i.WednesdayStart,
			&i.WednesdayEnd,
			&i.ThursdayStart,
			&i.ThursdayEnd,
			&i.FridayStart,
			&i.FridayEnd,
			&i.SaturdayStart,
			&i.SaturdayEnd,
			&i.SundayStart,
			&i.SundayEnd,
			&i.IpAddress,
			&i.Level,
			&i.Floor,
			&i.Side,
			&i.UserID,
			&i.Map,
			&i.IsHoliday,
			&i.HolidayStartDate,
			&i.HolidayEndDate,
			&i.HolidayStartTime,
			&i.HolidayEndTime,
			&i.CurrencyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreLocation = `-- name: UpdateStoreLocation :one
UPDATE store_locations
SET
    store_id = $2,
    mall_id = $3,
    address = $4,
    city = $5,
    state = $6,
    country_id = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    phone_no = $11,
    timezone = $12,
    isdeleted = $13,
    isblocked = $14,
    monday_start = $15,
    monday_end = $16,
    tuesday_start = $17,
    tuesday_end = $18,
    wednesday_start = $19,
    wednesday_end = $20,
    thursday_start = $21,
    thursday_end = $22,
    friday_start = $23,
    friday_end = $24,
    saturday_start = $25,
    saturday_end = $26,
    sunday_start = $27,
    sunday_end = $28,
    ip_address = $29,
    level = $30,
    floor = $31,
    side = $32,
    user_id = $33,
    map = $34,
    is_holiday = $35,
    holiday_start_date = $36,
    holiday_end_date = $37,
    holiday_start_time = $38,
    holiday_end_time = $39,
    currency_id = $40
WHERE id = $1
RETURNING id, store_id, mall_id, address, city, state, country_id, zip, latitude, longitude, phone_no, timezone, isdeleted, isblocked, monday_start, monday_end, tuesday_start, tuesday_end, wednesday_start, wednesday_end, thursday_start, thursday_end, friday_start, friday_end, saturday_start, saturday_end, sunday_start, sunday_end, ip_address, level, floor, side, user_id, map, is_holiday, holiday_start_date, holiday_end_date, holiday_start_time, holiday_end_time, currency_id, created_at
`

type UpdateStoreLocationParams struct {
	ID               int32       `json:"id"`
	StoreID          int32       `json:"store_id"`
	MallID           int32       `json:"mall_id"`
	Address          string      `json:"address"`
	City             string      `json:"city"`
	State            string      `json:"state"`
	CountryID        int32       `json:"country_id"`
	Zip              string      `json:"zip"`
	Latitude         pgtype.Text `json:"latitude"`
	Longitude        pgtype.Text `json:"longitude"`
	PhoneNo          pgtype.Text `json:"phone_no"`
	Timezone         pgtype.Text `json:"timezone"`
	Isdeleted        pgtype.Bool `json:"isdeleted"`
	Isblocked        pgtype.Bool `json:"isblocked"`
	MondayStart      pgtype.Time `json:"monday_start"`
	MondayEnd        pgtype.Time `json:"monday_end"`
	TuesdayStart     pgtype.Time `json:"tuesday_start"`
	TuesdayEnd       pgtype.Time `json:"tuesday_end"`
	WednesdayStart   pgtype.Time `json:"wednesday_start"`
	WednesdayEnd     pgtype.Time `json:"wednesday_end"`
	ThursdayStart    pgtype.Time `json:"thursday_start"`
	ThursdayEnd      pgtype.Time `json:"thursday_end"`
	FridayStart      pgtype.Time `json:"friday_start"`
	FridayEnd        pgtype.Time `json:"friday_end"`
	SaturdayStart    pgtype.Time `json:"saturday_start"`
	SaturdayEnd      pgtype.Time `json:"saturday_end"`
	SundayStart      pgtype.Time `json:"sunday_start"`
	SundayEnd        pgtype.Time `json:"sunday_end"`
	IpAddress        pgtype.Text `json:"ip_address"`
	Level            pgtype.Int4 `json:"level"`
	Floor            pgtype.Text `json:"floor"`
	Side             pgtype.Text `json:"side"`
	UserID           pgtype.Int4 `json:"user_id"`
	Map              pgtype.Text `json:"map"`
	IsHoliday        pgtype.Bool `json:"is_holiday"`
	HolidayStartDate pgtype.Date `json:"holiday_start_date"`
	HolidayEndDate   pgtype.Date `json:"holiday_end_date"`
	HolidayStartTime pgtype.Time `json:"holiday_start_time"`
	HolidayEndTime   pgtype.Time `json:"holiday_end_time"`
	CurrencyID       int32       `json:"currency_id"`
}

func (q *Queries) UpdateStoreLocation(ctx context.Context, arg UpdateStoreLocationParams) (StoreLocation, error) {
	row := q.db.QueryRow(ctx, updateStoreLocation,
		arg.ID,
		arg.StoreID,
		arg.MallID,
		arg.Address,
		arg.City,
		arg.State,
		arg.CountryID,
		arg.Zip,
		arg.Latitude,
		arg.Longitude,
		arg.PhoneNo,
		arg.Timezone,
		arg.Isdeleted,
		arg.Isblocked,
		arg.MondayStart,
		arg.MondayEnd,
		arg.TuesdayStart,
		arg.TuesdayEnd,
		arg.WednesdayStart,
		arg.WednesdayEnd,
		arg.ThursdayStart,
		arg.ThursdayEnd,
		arg.FridayStart,
		arg.FridayEnd,
		arg.SaturdayStart,
		arg.SaturdayEnd,
		arg.SundayStart,
		arg.SundayEnd,
		arg.IpAddress,
		arg.Level,
		arg.Floor,
		arg.Side,
		arg.UserID,
		arg.Map,
		arg.IsHoliday,
		arg.HolidayStartDate,
		arg.HolidayEndDate,
		arg.HolidayStartTime,
		arg.HolidayEndTime,
		arg.CurrencyID,
	)
	var i StoreLocation
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.MallID,
		&i.Address,
		&i.City,
		&i.State,
		&i.CountryID,
		&i.Zip,
		&i.Latitude,
		&i.Longitude,
		&i.PhoneNo,
		&i.Timezone,
		&i.Isdeleted,
		&i.Isblocked,
		&i.MondayStart,
		&i.MondayEnd,
		&i.TuesdayStart,
		&i.TuesdayEnd,
		&i.WednesdayStart,
		&i.WednesdayEnd,
		&i.ThursdayStart,
		&i.ThursdayEnd,
		&i.FridayStart,
		&i.FridayEnd,
		&i.SaturdayStart,
		&i.SaturdayEnd,
		&i.SundayStart,
		&i.SundayEnd,
		&i.IpAddress,
		&i.Level,
		&i.Floor,
		&i.Side,
		&i.UserID,
		&i.Map,
		&i.IsHoliday,
		&i.HolidayStartDate,
		&i.HolidayEndDate,
		&i.HolidayStartTime,
		&i.HolidayEndTime,
		&i.CurrencyID,
		&i.CreatedAt,
	)
	return i, err
}
