-- name: CreateStoreLocation :one
INSERT INTO store_locations (
    store_id,
    mall_id,
    address,
    city,
    state,
    country_id,
    zip,
    latitude,
    longitude,
    phone_no,
    timezone,
    isdeleted,
    isblocked,
    monday_start,
    monday_end,
    tuesday_start,
    tuesday_end,
    wednesday_start,
    wednesday_end,
    thursday_start,
    thursday_end,
    friday_start,
    friday_end,
    saturday_start,
    saturday_end,
    sunday_start,
    sunday_end,
    ip_address,
    level,
    floor,
    side,
    user_id,
    map,
    is_holiday,
    holiday_start_date,
    holiday_end_date,
    holiday_start_time,
    holiday_end_time,
    currency_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39
)
RETURNING id;

-- name: SelectStoreLocations :many
SELECT * FROM store_locations;

-- name: UpdateStoreLocation :one
UPDATE store_locations
SET
    store_id = $2,
    mall_id = $3,
    address = $4,
    city = $5,
    state = $6,
    country_id = $7,
    zip = $8,
    latitude = $9,
    longitude = $10,
    phone_no = $11,
    timezone = $12,
    isdeleted = $13,
    isblocked = $14,
    monday_start = $15,
    monday_end = $16,
    tuesday_start = $17,
    tuesday_end = $18,
    wednesday_start = $19,
    wednesday_end = $20,
    thursday_start = $21,
    thursday_end = $22,
    friday_start = $23,
    friday_end = $24,
    saturday_start = $25,
    saturday_end = $26,
    sunday_start = $27,
    sunday_end = $28,
    ip_address = $29,
    level = $30,
    floor = $31,
    side = $32,
    user_id = $33,
    map = $34,
    is_holiday = $35,
    holiday_start_date = $36,
    holiday_end_date = $37,
    holiday_start_time = $38,
    holiday_end_time = $39,
    currency_id = $40
WHERE id = $1
RETURNING *;

-- name: DeleteStoreLocation :one
DELETE FROM store_locations WHERE id = $1
RETURNING id;
